name: Elixir CI Workflow 🧪

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  elixir_ci:
    name: Elixir CI 🧪
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository 🛎️
      uses: actions/checkout@v2

    - name: Install Erlang/OTP + Elixir 🏗️
      id: setup-beam
      uses: erlef/setup-beam@v1
      with:
        otp-version: '24' # version range or exact (required)
        elixir-version: '1.13' # version range or exact (required)
        # install-hex: true (default)
        # install-rebar: true (default)
      # outputs: ${steps.setup-beam.outputs.(opt, elixir, rebar3)-version} (exact version installed)        

    - name: Restore dependency/build cache 🗃️
      uses: actions/cache@v2
      with:
        path: |
          ./beam.fuzz_dist/deps
          ./beam.fuzz_dist/_build
        # cache key is hierarchical: OS, otp-version, elixir-version, mix.lock
        key: ${{ runner.os }}-mix-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
        # restore keys are tried on cache misses, and only match the key prefix
        restore-keys: |
          ${{ runner.os }}-mix-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-
          ${{ runner.os }}-mix-${{ steps.setup-beam.outputs.otp-version }}-
          ${{ runner.os }}-mix-
        
    - name: Dependencies 🔗
      run: |
        mix deps.get
        mix deps.compile
      working-directory: ./beam.fuzz_dist

    - name: Code 🔧
      run: |
        mix format --check-formatted
        mix compile --warnings-as-errors
        mix credo --strict
        mix docs
      working-directory: ./beam.fuzz_dist
      # TODO: opaque type in Antidote client @spec, how to align?
      # mix dialyzer
 
    - name: Test 🦺
      run: |
        mix test --warnings-as-errors --cover --export-coverage default
      working-directory: ./beam.fuzz_dist
      # TODO: bug in mix doesn't respect test_coverage: [threshold: 0]
      # mix test.coverage

    - name: Artifacts 📚
      uses: actions/upload-artifact@v2
      with:
        name: doc-cover
        path: |
          ./beam.fuzz_dist/doc
          ./beam.fuzz_dist/cover
